# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b68754247aa7b08c0ea3707bb546705ed03d9acc5c8645d7ee27970582192ed20bde7097fbd83b379b0810203eaaaf69e1b5b519eb63f7590e773df75af074

test:
  secret_key_base: 358f9a56337d46d0bc7ba103c9b6e5337a06b9830f2780377a2ce352a28efeca7ab26f46b3b229f863c74960520969b0f54376b6f08e766e129e50ebd06be8ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
